//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Vector2 controlSymbolSelect
        {
            get
            {
                return SteamVR_Actions.default_controlSymbolSelect;
            }
        }
        
        public virtual SteamVR_Action_Boolean controlSymbolClick
        {
            get
            {
                return SteamVR_Actions.default_controlSymbolClick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 leftMoveValue
        {
            get
            {
                return SteamVR_Actions.default_leftMoveValue;
            }
        }
        
        public virtual SteamVR_Action_Boolean leftMoveClick
        {
            get
            {
                return SteamVR_Actions.default_leftMoveClick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 rightJoyStick
        {
            get
            {
                return SteamVR_Actions.default_rightJoyStick;
            }
        }
        
        public virtual SteamVR_Action_Single rightTriggerMech
        {
            get
            {
                return SteamVR_Actions.default_rightTriggerMech;
            }
        }
        
        public virtual SteamVR_Action_Single leftTriggerMech
        {
            get
            {
                return SteamVR_Actions.default_leftTriggerMech;
            }
        }
        
        public virtual SteamVR_Action_Boolean fireLeftGrapple
        {
            get
            {
                return SteamVR_Actions.default_fireLeftGrapple;
            }
        }
        
        public virtual SteamVR_Action_Boolean retractLeftGrapple
        {
            get
            {
                return SteamVR_Actions.default_retractLeftGrapple;
            }
        }
        
        public virtual SteamVR_Action_Boolean fireRightGrapple
        {
            get
            {
                return SteamVR_Actions.default_fireRightGrapple;
            }
        }
        
        public virtual SteamVR_Action_Boolean retractRightGrapple
        {
            get
            {
                return SteamVR_Actions.default_retractRightGrapple;
            }
        }
        
        public virtual SteamVR_Action_Vector2 leftHarken
        {
            get
            {
                return SteamVR_Actions.default_leftHarken;
            }
        }
        
        public virtual SteamVR_Action_Vector2 rightHarken
        {
            get
            {
                return SteamVR_Actions.default_rightHarken;
            }
        }
        
        public virtual SteamVR_Action_Boolean armLeftHarken
        {
            get
            {
                return SteamVR_Actions.default_armLeftHarken;
            }
        }
        
        public virtual SteamVR_Action_Boolean armRightHarken
        {
            get
            {
                return SteamVR_Actions.default_armRightHarken;
            }
        }
        
        public virtual SteamVR_Action_Single lSqueeze
        {
            get
            {
                return SteamVR_Actions.default_lSqueeze;
            }
        }
        
        public virtual SteamVR_Action_Single rSqueeze
        {
            get
            {
                return SteamVR_Actions.default_rSqueeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean switchToMelee
        {
            get
            {
                return SteamVR_Actions.default_switchToMelee;
            }
        }
        
        public virtual SteamVR_Action_Boolean turnOffLeftRight
        {
            get
            {
                return SteamVR_Actions.default_turnOffLeftRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean turnOffUpDown
        {
            get
            {
                return SteamVR_Actions.default_turnOffUpDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean turnOffBoth
        {
            get
            {
                return SteamVR_Actions.default_turnOffBoth;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
